Remove defaults for PageTitle and TestName
Siteimprove/alfa-integrations pull request #71
Opened 2024-08-27 11:48 UTC by jfer-siteimprove

Resolves #

2024-08-27 13:45 UTC, jfer-siteimprove commented
!pr extract

2024-08-28 08:28 UTC, Jym77 submitted a review, later dismissed

2024-08-28 08:28 UTC, Jym77 commented
@jfer-siteimprove I looked into it, `Option` don't really make sense here indeed. I removed some parameters that have become useless in various iterations.

2024-08-28 11:24 UTC, Jym77 commented
!pr extract

2024-08-28 11:26 UTC, rcj-siteimprove submitted a review, later dismissed

2024-08-28 13:29 UTC, Jym77 requested changes
Small clean up.

2024-08-28 13:29 UTC, Jym77 commented on packages/alfa-test-utils/src/report/sip.ts
> +          : gitInfo.getErrOr(Defaults.Name);
```suggestion
          : Defaults.Name;
```

2024-08-28 14:12 UTC, Jym77 approved these changes

2024-08-28 14:19 UTC, merged