II-8345: Update selenium integration documentation
Siteimprove/alfa-integrations pull request #80
Opened 2024-09-11 13:36 UTC by inga-balcune

Resolves #

2024-09-11 13:45 UTC, Jym77 requested changes
Copy/paste eagerness :-D 

Can you also remove the last sentence of https://github.com/Siteimprove/alfa-integrations/blob/main/packages/alfa-test-utils/docs/usage/scraping/advanced.md ?

2024-09-11 13:45 UTC, Jym77 commented on packages/alfa-test-utils/docs/usage/scraping/integrated.md
> +Install the `@siteimprove/alfa-playwright` package:
```suggestion
Install the `@siteimprove/alfa-selenium` package:
```

2024-09-11 13:45 UTC, Jym77 commented on packages/alfa-test-utils/docs/usage/scraping/integrated.md
> +$ npm install --save-dev @siteimprove/alfa-playwright
```suggestion
$ npm install --save-dev @siteimprove/alfa-selenium
```

2024-09-11 13:45 UTC, Jym77 commented on packages/alfa-test-utils/docs/usage/scraping/integrated.md
> +$ yarn add --dev @siteimprove/alfa-playwright
```suggestion
$ yarn add --dev @siteimprove/alfa-selenium
```

2024-09-11 13:46 UTC, Jym77 commented
🙈 The failed actions are on me 🤦

2024-09-11 13:47 UTC, inga-balcune commented
> actions are on m

Oops, and bad copy-paste job! It's getting late 🥱

2024-09-11 13:52 UTC, Jym77 requested changes
Can you also remove the last sentence of https://github.com/Siteimprove/alfa-integrations/blob/main/packages/alfa-test-utils/docs/usage/scraping/advanced.md ? 
(same reference to Selenium as in the Alfa hub)

2024-09-12 07:40 UTC, Jym77 approved these changes

2024-09-12 07:41 UTC, merged